Imports Microsoft.VisualBasic
Imports System
Namespace Telerik.Examples.WinControls.GridView.Validation
	Partial Public Class Form1
		''' <summary> 
		''' Required designer variable.
		''' </summary>
		Private components As System.ComponentModel.IContainer = Nothing

		''' <summary> 
		''' Clean up any resources being used.
		''' </summary>
		''' <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		Protected Overrides Sub Dispose(ByVal disposing As Boolean)
			If disposing AndAlso (components IsNot Nothing) Then
				components.Dispose()
			End If
			MyBase.Dispose(disposing)
		End Sub

		#Region "Component Designer generated code"

		''' <summary> 
		''' Required method for Designer support - do not modify 
		''' the contents of this method with the code editor.
		''' </summary>
		Private Sub InitializeComponent()
			Me.components = New System.ComponentModel.Container()
			Dim gridViewDecimalColumn1 As New Telerik.WinControls.UI.GridViewDecimalColumn()
			Dim gridViewDecimalColumn2 As New Telerik.WinControls.UI.GridViewDecimalColumn()
			Dim gridViewDecimalColumn3 As New Telerik.WinControls.UI.GridViewDecimalColumn()
			Dim gridViewDecimalColumn4 As New Telerik.WinControls.UI.GridViewDecimalColumn()
			Dim gridViewDecimalColumn5 As New Telerik.WinControls.UI.GridViewDecimalColumn()
			Me.radGridView1 = New Telerik.WinControls.UI.RadGridView()
			Me.orderDetailsBindingSource = New System.Windows.Forms.BindingSource(Me.components)
			Me.northwindDataSet = New Telerik.Examples.WinControls.DataSources.NorthwindDataSet()
			Me.order_DetailsTableAdapter = New Telerik.Examples.WinControls.DataSources.NorthwindDataSetTableAdapters.Order_DetailsTableAdapter()
			Me.radGroupBox1 = New Telerik.WinControls.UI.RadGroupBox()
			Me.radLabel1 = New Telerik.WinControls.UI.RadLabel()
			Me.radSpinEditor2 = New Telerik.WinControls.UI.RadSpinEditor()
			Me.radSpinEditor1 = New Telerik.WinControls.UI.RadSpinEditor()
			Me.radComboBox3 = New Telerik.WinControls.UI.RadDropDownList()
			Me.radComboBox2 = New Telerik.WinControls.UI.RadDropDownList()
			Me.radComboBox1 = New Telerik.WinControls.UI.RadDropDownList()
			CType(Me.settingsPanel, System.ComponentModel.ISupportInitialize).BeginInit()
			Me.settingsPanel.SuspendLayout()
			CType(Me.radGridView1, System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.radGridView1.MasterTemplate, System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.orderDetailsBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.northwindDataSet, System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.radGroupBox1, System.ComponentModel.ISupportInitialize).BeginInit()
			Me.radGroupBox1.SuspendLayout()
			CType(Me.radLabel1, System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.radSpinEditor2, System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.radSpinEditor1, System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.radComboBox3, System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.radComboBox2, System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.radComboBox1, System.ComponentModel.ISupportInitialize).BeginInit()
			Me.SuspendLayout()
			' 
			' settingsPanel
			' 
			Me.settingsPanel.Controls.Add(Me.radGroupBox1)
			Me.settingsPanel.Location = New System.Drawing.Point(844, 1)
			Me.settingsPanel.Size = New System.Drawing.Size(200, 585)
			Me.settingsPanel.ThemeName = "ControlDefault"
			Me.settingsPanel.Controls.SetChildIndex(Me.radGroupBox1, 0)
			' 
			' radGridView1
			' 
			Me.radGridView1.Dock = System.Windows.Forms.DockStyle.Fill
			Me.radGridView1.ForeColor = System.Drawing.Color.Black
			Me.radGridView1.Location = New System.Drawing.Point(0, 0)
			' 
			' 
			' 
			gridViewDecimalColumn1.DataType = GetType(Integer)
			gridViewDecimalColumn1.FieldName = "OrderID"
			gridViewDecimalColumn1.HeaderText = "OrderID"
			gridViewDecimalColumn1.IsAutoGenerated = True
			gridViewDecimalColumn1.Name = "OrderID"
			gridViewDecimalColumn2.DataType = GetType(Integer)
			gridViewDecimalColumn2.FieldName = "ProductID"
			gridViewDecimalColumn2.HeaderText = "ProductID"
			gridViewDecimalColumn2.IsAutoGenerated = True
			gridViewDecimalColumn2.Name = "ProductID"
			gridViewDecimalColumn3.DataType = GetType(Decimal)
			gridViewDecimalColumn3.FieldName = "UnitPrice"
			gridViewDecimalColumn3.HeaderText = "UnitPrice"
			gridViewDecimalColumn3.IsAutoGenerated = True
			gridViewDecimalColumn3.Name = "UnitPrice"
			gridViewDecimalColumn4.DataType = GetType(Short)
			gridViewDecimalColumn4.FieldName = "Quantity"
			gridViewDecimalColumn4.HeaderText = "Quantity"
			gridViewDecimalColumn4.IsAutoGenerated = True
			gridViewDecimalColumn4.Name = "Quantity"
			gridViewDecimalColumn5.DataType = GetType(Single)
			gridViewDecimalColumn5.FieldName = "Discount"
			gridViewDecimalColumn5.HeaderText = "Discount"
			gridViewDecimalColumn5.IsAutoGenerated = True
			gridViewDecimalColumn5.Name = "Discount"
			Me.radGridView1.MasterTemplate.Columns.Add(gridViewDecimalColumn1)
			Me.radGridView1.MasterTemplate.Columns.Add(gridViewDecimalColumn2)
			Me.radGridView1.MasterTemplate.Columns.Add(gridViewDecimalColumn3)
			Me.radGridView1.MasterTemplate.Columns.Add(gridViewDecimalColumn4)
			Me.radGridView1.MasterTemplate.Columns.Add(gridViewDecimalColumn5)
			Me.radGridView1.MasterTemplate.DataSource = Me.orderDetailsBindingSource
			Me.radGridView1.Name = "radGridView1"
			' 
			' 
			' 
			Me.radGridView1.RootElement.ForeColor = System.Drawing.Color.Black
			Me.radGridView1.Size = New System.Drawing.Size(1045, 587)
			Me.radGridView1.TabIndex = 1
			Me.radGridView1.ThemeName = "ControlDefault"
'			Me.radGridView1.CellFormatting += New Telerik.WinControls.UI.CellFormattingEventHandler(Me.radGridView1_CellFormatting);
'			Me.radGridView1.CellEndEdit += New Telerik.WinControls.UI.GridViewCellEventHandler(Me.radGridView1_CellEndEdit);
'			Me.radGridView1.RowFormatting += New Telerik.WinControls.UI.RowFormattingEventHandler(Me.radGridView1_RowFormatting);
'			Me.radGridView1.CellValidating += New Telerik.WinControls.UI.CellValidatingEventHandler(Me.radGridView1_CellValidating);
			' 
			' orderDetailsBindingSource
			' 
			Me.orderDetailsBindingSource.DataMember = "Order Details"
			Me.orderDetailsBindingSource.DataSource = Me.northwindDataSet
			' 
			' northwindDataSet
			' 
			Me.northwindDataSet.DataSetName = "NorthwindDataSet"
			Me.northwindDataSet.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
			' 
			' order_DetailsTableAdapter
			' 
			Me.order_DetailsTableAdapter.ClearBeforeFill = True
			' 
			' radGroupBox1
			' 
			Me.radGroupBox1.Anchor = System.Windows.Forms.AnchorStyles.Top
			Me.radGroupBox1.Controls.Add(Me.radLabel1)
			Me.radGroupBox1.Controls.Add(Me.radSpinEditor2)
			Me.radGroupBox1.Controls.Add(Me.radSpinEditor1)
			Me.radGroupBox1.Controls.Add(Me.radComboBox3)
			Me.radGroupBox1.Controls.Add(Me.radComboBox2)
			Me.radGroupBox1.Controls.Add(Me.radComboBox1)
			Me.radGroupBox1.FooterImageIndex = -1
			Me.radGroupBox1.FooterImageKey = ""
			Me.radGroupBox1.ForeColor = System.Drawing.Color.Black
			Me.radGroupBox1.HeaderImageIndex = -1
			Me.radGroupBox1.HeaderImageKey = ""
			Me.radGroupBox1.HeaderMargin = New System.Windows.Forms.Padding(0)
			Me.radGroupBox1.HeaderText = "Column restrictions:"
			Me.radGroupBox1.Location = New System.Drawing.Point(10, 46)
			Me.radGroupBox1.Name = "radGroupBox1"
			' 
			' 
			' 
			Me.radGroupBox1.RootElement.ForeColor = System.Drawing.Color.Black
			Me.radGroupBox1.Size = New System.Drawing.Size(180, 190)
			Me.radGroupBox1.TabIndex = 1
			Me.radGroupBox1.Text = "Column restrictions:"
			Me.radGroupBox1.ThemeName = "ControlDefault"
			' 
			' radLabel1
			' 
			Me.radLabel1.ForeColor = System.Drawing.Color.Black
			Me.radLabel1.Location = New System.Drawing.Point(17, 110)
			Me.radLabel1.Name = "radLabel1"
			' 
			' 
			' 
			Me.radLabel1.RootElement.ForeColor = System.Drawing.Color.Black
			Me.radLabel1.Size = New System.Drawing.Size(23, 14)
			Me.radLabel1.TabIndex = 5
			Me.radLabel1.Text = "and"
			' 
			' radSpinEditor2
			' 
			Me.radSpinEditor2.BackColor = System.Drawing.Color.White
			Me.radSpinEditor2.ForeColor = System.Drawing.Color.Black
			Me.radSpinEditor2.Location = New System.Drawing.Point(17, 156)
			Me.radSpinEditor2.Name = "radSpinEditor2"
			' 
			' 
			' 
			Me.radSpinEditor2.RootElement.AutoSizeMode = Telerik.WinControls.RadAutoSizeMode.WrapAroundChildren
			Me.radSpinEditor2.RootElement.ForeColor = System.Drawing.Color.Black
			Me.radSpinEditor2.ShowBorder = True
			Me.radSpinEditor2.Size = New System.Drawing.Size(78, 20)
			Me.radSpinEditor2.TabIndex = 4
			Me.radSpinEditor2.Text = "radSpinEditor2"
'			Me.radSpinEditor2.ValueChanged += New System.EventHandler(Me.radSpinEditor2_ValueChanged);
			' 
			' radSpinEditor1
			' 
			Me.radSpinEditor1.BackColor = System.Drawing.Color.White
			Me.radSpinEditor1.ForeColor = System.Drawing.Color.Black
			Me.radSpinEditor1.Location = New System.Drawing.Point(17, 84)
			Me.radSpinEditor1.Name = "radSpinEditor1"
			' 
			' 
			' 
			Me.radSpinEditor1.RootElement.AutoSizeMode = Telerik.WinControls.RadAutoSizeMode.WrapAroundChildren
			Me.radSpinEditor1.RootElement.ForeColor = System.Drawing.Color.Black
			Me.radSpinEditor1.ShowBorder = True
			Me.radSpinEditor1.Size = New System.Drawing.Size(78, 20)
			Me.radSpinEditor1.TabIndex = 3
'			Me.radSpinEditor1.ValueChanged += New System.EventHandler(Me.radSpinEditor1_ValueChanged);
			' 
			' radComboBox3
			' 
			Me.radComboBox3.ForeColor = System.Drawing.Color.Black
			Me.radComboBox3.Location = New System.Drawing.Point(17, 130)
			Me.radComboBox3.Name = "radComboBox3"
			' 
			' 
			' 
			Me.radComboBox3.RootElement.ForeColor = System.Drawing.Color.Black
			Me.radComboBox3.Size = New System.Drawing.Size(147, 20)
			Me.radComboBox3.TabIndex = 2
			Me.radComboBox3.Text = "radComboBox3"
'			Me.radComboBox3.SelectedIndexChanged += New Telerik.WinControls.UI.Data.PositionChangedEventHandler(Me.radComboBox3_SelectedIndexChanged);
			' 
			' radComboBox2
			' 
			Me.radComboBox2.ForeColor = System.Drawing.Color.Black
			Me.radComboBox2.Location = New System.Drawing.Point(17, 58)
			Me.radComboBox2.Name = "radComboBox2"
			' 
			' 
			' 
			Me.radComboBox2.RootElement.ForeColor = System.Drawing.Color.Black
			Me.radComboBox2.Size = New System.Drawing.Size(147, 20)
			Me.radComboBox2.TabIndex = 1
			Me.radComboBox2.Text = "radComboBox2"
'			Me.radComboBox2.SelectedIndexChanged += New Telerik.WinControls.UI.Data.PositionChangedEventHandler(Me.radComboBox2_SelectedIndexChanged);
			' 
			' radComboBox1
			' 
			Me.radComboBox1.ForeColor = System.Drawing.Color.Black
			Me.radComboBox1.Location = New System.Drawing.Point(17, 32)
			Me.radComboBox1.Name = "radComboBox1"
			' 
			' 
			' 
			Me.radComboBox1.RootElement.ForeColor = System.Drawing.Color.Black
			Me.radComboBox1.Size = New System.Drawing.Size(147, 20)
			Me.radComboBox1.TabIndex = 0
			Me.radComboBox1.Text = "radComboBox1"
'			Me.radComboBox1.SelectedIndexChanged += New Telerik.WinControls.UI.Data.PositionChangedEventHandler(Me.radComboBox1_SelectedIndexChanged);
			' 
			' Form1
			' 
			Me.AutoScaleDimensions = New System.Drawing.SizeF(6F, 13F)
			Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
			Me.Controls.Add(Me.radGridView1)
			Me.Name = "Form1"
			Me.Size = New System.Drawing.Size(1045, 587)
			Me.Controls.SetChildIndex(Me.radGridView1, 0)
			Me.Controls.SetChildIndex(Me.settingsPanel, 0)
			CType(Me.settingsPanel, System.ComponentModel.ISupportInitialize).EndInit()
			Me.settingsPanel.ResumeLayout(False)
			CType(Me.radGridView1.MasterTemplate, System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.radGridView1, System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.orderDetailsBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.northwindDataSet, System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.radGroupBox1, System.ComponentModel.ISupportInitialize).EndInit()
			Me.radGroupBox1.ResumeLayout(False)
			Me.radGroupBox1.PerformLayout()
			CType(Me.radLabel1, System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.radSpinEditor2, System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.radSpinEditor1, System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.radComboBox3, System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.radComboBox2, System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.radComboBox1, System.ComponentModel.ISupportInitialize).EndInit()
			Me.ResumeLayout(False)
			Me.PerformLayout()

		End Sub

		#End Region

		Private WithEvents radGridView1 As Telerik.WinControls.UI.RadGridView
		Private northwindDataSet As Telerik.Examples.WinControls.DataSources.NorthwindDataSet
		Private orderDetailsBindingSource As System.Windows.Forms.BindingSource
		Private order_DetailsTableAdapter As Telerik.Examples.WinControls.DataSources.NorthwindDataSetTableAdapters.Order_DetailsTableAdapter
		Private radGroupBox1 As Telerik.WinControls.UI.RadGroupBox
		Private WithEvents radComboBox1 As Telerik.WinControls.UI.RadDropDownList
		Private WithEvents radComboBox3 As Telerik.WinControls.UI.RadDropDownList
		Private WithEvents radComboBox2 As Telerik.WinControls.UI.RadDropDownList
		Private WithEvents radSpinEditor1 As Telerik.WinControls.UI.RadSpinEditor
		Private WithEvents radSpinEditor2 As Telerik.WinControls.UI.RadSpinEditor
		Private radLabel1 As Telerik.WinControls.UI.RadLabel
	End Class
End Namespace
